server:
  port: 20000

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
  thymeleaf:
    cache: false
  redis:
    host: 192.168.163.129
    port: 6379
