spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
#  elasticsearch:
#    rest:
#      uris: 192.168.163.129
server:
  port: 12000
