spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
  thymeleaf:
    cache: false
  redis:
    host: 192.168.163.129
  session:
    store-type: redis
#  elasticsearch:
#    rest:
#      uris: 192.168.163.129
server:
  port: 12000

